// ********RoostGPT********
/*
Test generated by RoostGPT for test Go-rahul-jwt-test using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=isEd_03b64c2821
ROOST_METHOD_SIG_HASH=isEd_3330842b8e

FUNCTION_DEF=func isEd() bool 
Scenario 1: Testing for EdDSA algorithm

Details:
  Description: This test is meant to check whether the function correctly identifies the "EdDSA" algorithm when the flagAlg variable is set to "EdDSA".
Execution:
  Arrange: Set the flagAlg variable to "EdDSA".
  Act: Invoke the isEd() function.
  Assert: Use Go testing facilities to verify that the actual result is true.
Validation:
  The choice of assertion is to confirm that the function correctly identifies the "EdDSA" algorithm. The expected result is true because the flagAlg variable is set to "EdDSA". This test is important to ensure that the function can correctly identify the "EdDSA" algorithm.

Scenario 2: Testing for non-EdDSA algorithm

Details:
  Description: This test is meant to check whether the function correctly identifies non-EdDSA algorithms when the flagAlg variable is set to any other value.
Execution:
  Arrange: Set the flagAlg variable to a non-EdDSA value.
  Act: Invoke the isEd() function.
  Assert: Use Go testing facilities to verify that the actual result is false.
Validation:
  The choice of assertion is to confirm that the function correctly identifies non-EdDSA algorithms. The expected result is false because the flagAlg variable is not set to "EdDSA". This test is important to ensure that the function can correctly identify non-EdDSA algorithms.

Scenario 3: Testing for empty algorithm

Details:
  Description: This test is meant to check whether the function correctly identifies an empty algorithm when the flagAlg variable is not set.
Execution:
  Arrange: Do not set the flagAlg variable.
  Act: Invoke the isEd() function.
  Assert: Use Go testing facilities to verify that the actual result is false.
Validation:
  The choice of assertion is to confirm that the function correctly identifies an empty algorithm. The expected result is false because the flagAlg variable is not set. This test is important to ensure that the function can correctly identify an empty algorithm.
*/

// ********RoostGPT********


package main

import (
	"flag"
	"testing"
)







func TestisEd(t *testing.T) {

	tests := []struct {
		name     string
		flagAlg  string
		expected bool
	}{
		{
			name:     "Testing for EdDSA algorithm",
			flagAlg:  "EdDSA",
			expected: true,
		},
		{
			name:     "Testing for non-EdDSA algorithm",
			flagAlg:  "RS256",
			expected: false,
		},
		{
			name:     "Testing for empty algorithm",
			flagAlg:  "",
			expected: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {

			flagAlg = flag.String("alg", tt.flagAlg, algHelp())

			result := isEd()

			if result != tt.expected {
				t.Errorf("isEd() = %v, want %v", result, tt.expected)
			} else {
				t.Logf("Success: Expected output %v and got %v", tt.expected, result)
			}
		})
	}
}
